## Repaso Matrices - Taller 3

Este taller debe ser entregado a más tardar el viernes 3 de noviembre a medianoche (11:59pm).

1. **20 pts** Construya el algoritmo de multiplicación de matrices y encuentre el resultado de las siguientes operaciones.




## Multiplicación de matrices

In [13]:
import numpy as np
def multiplicacion_matrices(A,B):
    if len(A.shape)<len(B.shape):
        return "No se puede realizar la multiplicación, dimensión de A=({},{})".format(len((A.shape)),len((A.shape)))
    if len(B.shape)==1:
        B=B.reshape(B.shape[0],1)
    if  A.shape[1] !=B.shape[0]:
        return "No se puede realizar la multiplicación, número de columnas en A distinto al número de filas en B" 
    p=B.shape[1]
    m=A.shape[0]
    G=np.zeros((m,p))
    for i in range(m):
        for j in range(p):
            for k in range(B.shape[0]):
                G[i,j]+=A[i,k]*B[k,j]
    if B.shape[1]==1:
        G=G.reshape(G.shape[0],)
                
    return G

a.

 <img src ='./img/matrix1.png' width=200px>
 

In [14]:
A=np.array([[5,-4,-2],[5,-5,4],[2,5,-4],[-5,4,3],[3,-4,-3]])
B=np.array([5,-2,-3])
A,B

(array([[ 5, -4, -2],
        [ 5, -5,  4],
        [ 2,  5, -4],
        [-5,  4,  3],
        [ 3, -4, -3]]),
 array([ 5, -2, -3]))

In [15]:
multiplicacion_matrices(A,B)

array([ 39.,  23.,  12., -42.,  32.])

In [17]:
np.dot(A,B) #Confirmar

array([ 39,  23,  12, -42,  32])

 b.
 
  <img src ='./img/matrix2.png' width=200px>



In [20]:
A=np.array([[0,1,-1,3],[5,-5,-2,2],[1,0,4,5]])
B=np.array([[0,-3],[-2,-1],[3,-3]])
A,B

(array([[ 0,  1, -1,  3],
        [ 5, -5, -2,  2],
        [ 1,  0,  4,  5]]),
 array([[ 0, -3],
        [-2, -1],
        [ 3, -3]]))

In [21]:
multiplicacion_matrices(A,B)

'No se puede realizar la multiplicación número de columnas en A distinto al número de filas en B'

c. 

  <img src ='./img/matrix3.png' width=200px>

  

In [23]:
A=np.array([[2,-5,5,1],[5,2,-7,-6],[-6,-1,7,-4],[5,4,1,-5]])
B=np.array([[0,4,-7,1,-6],[-1,-6,-5,1,1],[2,-1,-6,5,-5],[-3,-6,6,3,5]])
A,B

(array([[ 2, -5,  5,  1],
        [ 5,  2, -7, -6],
        [-6, -1,  7, -4],
        [ 5,  4,  1, -5]]),
 array([[ 0,  4, -7,  1, -6],
        [-1, -6, -5,  1,  1],
        [ 2, -1, -6,  5, -5],
        [-3, -6,  6,  3,  5]]))

In [25]:
multiplicacion_matrices(A,B)

array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

In [26]:
np.dot(A,B) #Confirmar

array([[ 12,  27, -13,  25, -37],
       [  2,  51, -39, -46, -23],
       [ 27,  -1, -19,  16, -20],
       [ 13,  25, -91,  -1, -56]])

 Utilizando el ejercicio anterior, demuestre que la multiplicación no es conmutativa **10 pts**.

## Conmutatividad

a)

In [27]:
A=np.array([[5,-4,-2],[5,-5,4],[2,5,-4],[-5,4,3],[3,-4,-3]])
B=np.array([5,-2,-3])
A,B

(array([[ 5, -4, -2],
        [ 5, -5,  4],
        [ 2,  5, -4],
        [-5,  4,  3],
        [ 3, -4, -3]]),
 array([ 5, -2, -3]))

In [29]:
multiplicacion_matrices(B,A)

'No se puede realizar la multiplicación dimensión de A=(1,1)'

b)

In [31]:
A=np.array([[0,1,-1,3],[5,-5,-2,2],[1,0,4,5]])
B=np.array([[0,-3],[-2,-1],[3,-3]])
A,B

(array([[ 0,  1, -1,  3],
        [ 5, -5, -2,  2],
        [ 1,  0,  4,  5]]),
 array([[ 0, -3],
        [-2, -1],
        [ 3, -3]]))

In [33]:
multiplicacion_matrices(B,A)

'No se puede realizar la multiplicación número de columnas en A distinto al número de filas en B'

c)

In [35]:
A=np.array([[2,-5,5,1],[5,2,-7,-6],[-6,-1,7,-4],[5,4,1,-5]])
B=np.array([[0,4,-7,1,-6],[-1,-6,-5,1,1],[2,-1,-6,5,-5],[-3,-6,6,3,5]])
A,B

(array([[ 2, -5,  5,  1],
        [ 5,  2, -7, -6],
        [-6, -1,  7, -4],
        [ 5,  4,  1, -5]]),
 array([[ 0,  4, -7,  1, -6],
        [-1, -6, -5,  1,  1],
        [ 2, -1, -6,  5, -5],
        [-3, -6,  6,  3,  5]]))

In [37]:
multiplicacion_matrices(B,A)

'No se puede realizar la multiplicación número de columnas en A distinto al número de filas en B'

2. **[40 pts]** Utilizando el algoritmo de reducción Gaussiana, resuelva los siguientes sistemas de ecuaciones:

a.

 <img src ='./img/gaussian1.png' width=300px align=center>

 b.

 <img src ='./img/gaussian2.png' width=300px>

3. **30 pts** Un sistema de tres osciladores acoplados, tiene las siguientes ecuaciones de movimiento:

<img src='./img/eqmotion.png' width=200>

Al reemplazar $x_1=c_1e^{i\omega t},x_2=c_2e^{i\omega t},x_3=c_3e^{i\omega t}$ se obtienen las siguientes ecuaciones algebraicas

<img src='./img/algeq.png'  width=200>

Para encontrar las frecuencias, se puede pensar lo anterior como un problema de valor propio regido por la ecuación

$M\vec{v} = -\omega^2 \vec{v}$

donde $\vec{v}$ es el vector de amplitudes $c_1,c_2,c_3$ y $-\omega^2$ los valores propios. Utilizando el método de la potencia, encuentre la frecuencia máxima y mínima de oscilación del sistema y sus amplitudes asociadas para cada caso (modo normal).




## Reduccion Gaussiana

In [ ]:
def gaussian_elimination(A,b):
    return None