## Repaso Matrices - Taller 3

Este taller debe ser entregado a más tardar el viernes 3 de noviembre a medianoche (11:59pm).

### 1. Multiplicación de matrices

**[20 pts]** Construya el algoritmo de multiplicación de matrices y encuentre el resultado de las siguientes operaciones.

In [9]:
import numpy as np
def multiplicacion_matrices(A,B):
    if len(A.shape)<len(B.shape):
        return "No se puede realizar la multiplicación, dimensión de A=({},{})".format(len((A.shape)),len((A.shape)))
    if len(B.shape)==1:
        B=B.reshape(B.shape[0],1)
    if  A.shape[1] !=B.shape[0]:
        return "No se puede realizar la multiplicación, número de columnas en A distinto al número de filas en B" 
    p=B.shape[1]
    m=A.shape[0]
    G=np.zeros((m,p))
    for i in range(m):
        for j in range(p):
            for k in range(B.shape[0]):
                G[i,j]+=A[i,k]*B[k,j]
    if B.shape[1]==1:
        G=G.reshape(G.shape[0],)
                
    return G

a.

 <img src ='./img/matrix1.png' width=200px>

In [10]:
####Inciso A####
A=np.array([[5,-4,-2],[5,-5,4],[2,5,-4],[-5,4,3],[3,-4,-3]])
B=np.array([5,-2,-3])
print(np.dot(A,B)) #Confirmar
multiplicacion_matrices(A,B)


[ 39  23  12 -42  32]


array([ 39.,  23.,  12., -42.,  32.])

 b.
 
  <img src ='./img/matrix2.png' width=200px>

In [11]:
###Inciso B##
A=np.array([[0,1,-1,3],[5,-5,-2,2],[1,0,4,5]])
B=np.array([[0,-3],[-2,-1],[3,-3]])
multiplicacion_matrices(A,B)


'No se puede realizar la multiplicación, número de columnas en A distinto al número de filas en B'

    c. 

  <img src ='./img/matrix3.png' width=200px>

In [12]:
####Inciso C####
A=np.array([[2,-5,5,1],[5,2,-7,-6],[-6,-1,7,-4],[5,4,1,-5]])
B=np.array([[0,4,-7,1,-6],[-1,-6,-5,1,1],[2,-1,-6,5,-5],[-3,-6,6,3,5]])
multiplicacion_matrices(A,B)

array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

  **[10 pts]** Utilizando dos matrices cuadradas, demuestre que la multiplicación no es conmutativa.

  Suponiendo las siguientes matrices:
  
\begin{equation}

  \begin{bmatrix}
  1 & 2\\
  3 & 4  
  \end{bmatrix}
  
  \begin{bmatrix}
  5 & 6\\
  7 & 8  
  \end{bmatrix}
  
\end{equation}



In [20]:
M1 = np.array([[1,2],[3,4]])
M2 = np.array([[5,6],[7,7]])

print(multiplicacion_matrices(M1,M2)) == multiplicacion_matrices(M2,M1)

[[19. 20.]
 [43. 46.]]


array([[False, False],
       [False, False]])

### 2. Reducción gaussiana
**[40 pts]** Utilizando el algoritmo de reducción Gaussiana, resuelva los siguientes sistemas de ecuaciones:

a.

 <img src ='./img/gaussian1.png' width=300px align=center>

 b.

 <img src ='./img/gaussian2.png' width=300px>

### 3. Valores y vectores propios

**[30 pts]** Un sistema de tres osciladores acoplados, tiene las siguientes ecuaciones de movimiento:

<img src='./img/eqmotion.png' width=200>

Al reemplazar $x_1=c_1e^{i\omega t},x_2=c_2e^{i\omega t},x_3=c_3e^{i\omega t}$ se obtienen las siguientes ecuaciones algebraicas

<img src='./img/algeq.png'  width=200>

Para encontrar las frecuencias, se puede pensar lo anterior como un problema de valor propio regido por la ecuación

$M\vec{v} = -\omega^2 \vec{v}$

donde $\vec{v}$ es el vector de amplitudes $c_1,c_2,c_3$ y $-\omega^2$ los valores propios. Utilizando el método de la potencia, encuentre la frecuencia máxima y mínima de oscilación del sistema y sus amplitudes asociadas para cada caso (modo normal). En su solución pruebe $k_{11}=k_{22}=k_{33}=-2\kappa, k_{12}=k_{21}=k_{23}=k_{32}=\kappa, k_{13}=k_{31}=0$.


