## Matrices y eliminación de Gauss Jordan

Un sistema de ecuaciones lineales de $n$ variables se puede escribir 

$$
\begin{align*}
A \mathbf{x} = \mathbf{b}
\end{align*}
$$

donde $A \in \mathbb{M}_{n \times n}$ y $\mathbf{x}, \mathbf{b}$ son vectores en $\mathbb{R}^n$. El método de eliminación de Gauss Jordan consiste en realizar operaciones elementales sobre la matriz extendida $[A|\mathbf{b}]$ hasta obtener una matriz triangular superior. Entonces, un sistema de ecuaciones lineales

$$
\begin{cases}
& 2x_0 + x_1 + x_2 = 8 \\ 
& x_0 + x_1 -2x_2 = -2 \\
& 5x_0 + 10x_1 +5x_2 = 10
\end{cases}
$$

se puede reescribir de forma matricial 

$$
A = \begin{bmatrix}
2 & 1 & 1 \\
1 & 1 & -2 \\
5 &10 & 5
\end{bmatrix} \qquad \qquad \mathbf{x} = \begin{bmatrix} x_0 \\ x_1 \\ x_2 \end{bmatrix} \qquad \qquad \mathbf{b} = \begin{bmatrix} 8 \\ -2 \\ 10 \end{bmatrix}
$$

Siguiendo el algoritmo de Gauss, podemos llegar a la versión reducida utilizando operaciones elementales de fila, es decir reemplazando la fila $i$-ésima por

$$
R_i^\prime = R_i + kR_j
$$

Para al final obtener

$$
[A|b] = \left[ \begin{array}{ccc|c}
2 & 1 & 1 & 8 \\
0 & 0.5 & -2.5 & -6 \\
0 &0 & 40 & 80
\end{array} \right]
$$

donde la solución es casi trivial. El reto de la clase de hoy será escribir el algoritmo que retorne las matrices de su forma reducida.

En primer lugar, debemos recorrer todas las columnas menos la última de la matriz $A$, y para cada una de estas recorrer todas las filas desde la que está debajo de la diagonal hasta el final.

In [42]:
import numpy as np

In [43]:
A = np.array([[2,1,1],\
     [1,1,-2],
     [5,10,5]])

In [44]:
A

array([[ 2,  1,  1],
       [ 1,  1, -2],
       [ 5, 10,  5]])

In [63]:
b = np.array([8,-2,10])

In [64]:
b

array([ 8, -2, 10])

In [65]:
n = np.shape(A)[0]
M = np.zeros(shape=(n,n+1))

In [66]:
M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
M[:,0:n] = A

In [68]:
M

array([[ 2.,  1.,  1.,  0.],
       [ 1.,  1., -2.,  0.],
       [ 5., 10.,  5.,  0.]])

In [69]:
M[:,n] = b

In [70]:
M

array([[ 2.,  1.,  1.,  8.],
       [ 1.,  1., -2., -2.],
       [ 5., 10.,  5., 10.]])

In [75]:
# j son columnas, i son filas
for j in range(n-1):
    for i in range(j+1,n):
        print(i,j)

1 0
2 0
2 1
